src/tree/render.js
rounded elbow paths, should work regardless of the two points relation to each other. rdef can be changed to get larger/smaller curve on the corner.
=> feat: change default paths to rounded elbow

src/data.js, src/ext.js, src/utils/tree-transform.js
Adds attributes for color, labels and sublabels. Also improves the data page mechanism and adds a sanity limit.
=> feat: update data handling

src/tree/path.js
=> fix: Don't use Math.sign

src/card/card.js, src/index.js, src/tree/box.js, src/treeCss.css, src/utils/selections.js
Merging into selections branch
=> feat: re-render during selections

src/tree/transform.js, src/treeCss.css
Will add a 36px margin on top and bottom, even if there is no button. Not worth the effort to only add it when needed IMO.
=> fix: Bounding box

src/index.js, src/tree/render.js, src/tree/transform.js
- Does not animate on first render
- Does not render when layout is changed, so no animation for changes in PP or selections
=> fix: Limit animation to traversing

src/card/__tests__/card.spec.js, src/card/card.js, src/styles/nodes.less, src/tree/box.js, src/tree/path.js, src/tree/path.spec.js, src/tree/position.js
Showing that we don't know where the nodes actually connect. Request by Christofer.
=> Fix: Show multiple dummy root nodes

src/styles/nodes.less
make sure you cannot select text on the expand buttons either.
=> fix: no text select for buttons

src/index.js, src/utils/viewstate-utils.js
This fixes view state to be correct in snapshots in Storytelling
=> fix: setting viewstate in snapshot data

src/index.js, src/tree/render.js, src/tree/transform.js
- only allow zoom/pan in analysis
- Make sure that `paintTree` and `setZooming` runs when `constraints` is updated
=> fix: limit zoom to analysis mode

src/card/card.js, src/utils/__tests__/styling.spec.js, src/utils/styling.js
This was in a PR from @Caele that never was merged.
=> feat: measure label

src/styles/tooltip.less, src/tree/box.js, src/tree/render.js, src/tree/tooltip.js
@Caele @eliseeborn This seems to work for me. Am I missing something here?
=> fix: tooltip close on scroll and click

src/tree/transform.js
Still can pan efter the context menu has appeared. Could block that with checking if the menu is in the DOM, but feels a bit hacky.
=> fix: bubble touch events to trigger longtap

.circleci/config.yml
fix chrome version in circleci config
=> chore: update chrome browserless

yarn.lock
Upgrade yarn dependencies to resolve security vulnerabilities
=> fix: upgrade dependencies

src/__tests__/snapshot.spec.js, src/extension/ext-raw.js, src/index.js, src/snapshot.js, src/tree/__tests__/path.spec.js, src/tree/__tests__/position.spec.js, src/tree/__tests__/transform.spec.js, src/tree/box.js, src/tree/path.js, src/tree/position.js, src/tree/render.js, src/tree/transform.js
Full tree mode for org chart
TODO
=> feat: expand full tree

src/object-properties.js
=> feat: new default style

src/extension/ext-raw.js
I guess the lint has updated as well, but main change on line 205/207
=> fix: add translation string card appearance

package.json
Bumping the minor version, keeping the patch number for actual patching
=> chore: v0.8.0

package.json, scripts/version-qext.js
Need to patch this for June release as well.
=> feat: add version to qext file (#155)

src/tree/box.js, src/tree/render.js
Only two lines are actually changed. The rest is linter changes. Look for the constraints.active -> constrains.select changes
=> fix: use correct constraint for selections

src/utils/tree-utils.js, yarn.lock
Didn't see any changes just changing yarn.lock, had to change another file.
=> chore: bump deps

package.json, src/card/__tests__/card.spec.js, src/card/card.js, src/utils/encoder.js, yarn.lock
Title encoding similar to date picker https://github.com/qlik-oss/SenseDateRangePicker/blob/master/src/lib/encoder.js
=> fix: title encoding

src/tree/tooltip.js
missed a visual bug caused by my previous pr
=> fix: text br tags

src/card/__tests__/card.spec.js, src/style-defaults.js, src/utils/__tests__/styling.spec.js
the styling the code defaulted to was different than what was in the object properties, and I chose the wrong ones when making the styling-defaults file
=> fix: change to correct default styling

.circleci/config.yml, .github/CONTRIBUTION.md, .gitignore, core/package.json, package.json, tools/build.js, tools/copy-ext.js, tools/prepare-sn-pack.js, tools/validate-nebula-package.js, yarn.lock
mostly just checked what @haxxmaxx had done in action button
=> chore: update build and release processes

src/locale/locales/de.json, src/locale/locales/es.json, src/locale/locales/fr.json, src/locale/locales/it.json, src/locale/locales/ja.json, src/locale/locales/ko.json, src/locale/locales/nl.json, src/locale/locales/pl.json, src/locale/locales/pt.json, src/locale/locales/ru.json, src/locale/locales/sv.json, src/locale/locales/tr.json, src/locale/locales/zh-CN.json
chore(translations): UI bus - 2023-04-14
- Update translations related to: 26265fd - chore: update localization files (#285)
=> chore(translations): UI bus - 2023-04-14

package.json, src/card/__tests__/card.spec.js, src/card/card.js, src/selections-handler.js, src/tree/__tests__/path.spec.js, src/tree/__tests__/transform.spec.js, src/tree/box.js, src/tree/path.js, src/tree/render.js, src/tree/tooltip.js, src/tree/transform.js, src/utils/__tests__/styling.spec.js, src/utils/__tests__/tree-utils.spec.js, src/utils/color-utils.js, src/utils/tree-utils.js, tools/validate-nebula-package.js
In preparation for the move to sn-gh-workflows. Prettier has not checked/ran on dependency update
=> chore: cleanup lint and run prettier
